In [1]:

import array as arr
a = arr.array('i', [1, 2, 3])
print("The new created array is : ", end=" ")
for i in range(0, 3):
    print(a[i], end=" ")
print()
b = arr.array('d', [2.5, 3.2, 3.3])
print("\nThe new created array is : ", end=" ")
for i in range(0, 3):
    print(b[i], end=" ")

c = arr.array('u',['a', 'b','c'])
for i in range(0, len(c)):
    print(c[i], end=" ")


The new created array is :  1 2 3 

The new created array is :  2.5 3.2 3.3 a b c 

In [2]:
print(c[1])

c.append('e')

print(c)

c.pop(2)

print(c)

print(len(c))

c.remove('e')

print(c)

b
array('u', 'abce')
array('u', 'abe')
3
array('u', 'ab')


In [3]:
ar = arr.array('i',[0])

for i in range(0,20):
    ar.append(i)

print(ar)

sl_ar = ar[1:5]

print(ar)
print(sl_ar)

print(ar[5:])

print(ar.index(10))

ar[ar.index(10)] = 100

print(ar)

cnt = ar.count(11)

print(cnt)

ar.reverse()

print(ar)

ar.extend([122,3241,413,12,1213,42])

print(ar)

array('i', [0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
array('i', [0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
array('i', [0, 1, 2, 3])
array('i', [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
11
array('i', [0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 100, 11, 12, 13, 14, 15, 16, 17, 18, 19])
1
array('i', [19, 18, 17, 16, 15, 14, 13, 12, 11, 100, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 0])
array('i', [19, 18, 17, 16, 15, 14, 13, 12, 11, 100, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 0, 122, 3241, 413, 12, 1213, 42])


In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [8,8,9,8, 14]])

print(arr)

print(np.__version__)
print(type(arr))

print('number of dimensions :', arr.ndim) 


arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[ 1  2  3  4  5]
 [ 8  8  9  8 14]]
1.24.4
<class 'numpy.ndarray'>
number of dimensions : 2
[[[[[1 2 3 4]]]]]
number of dimensions : 5
